### ISSUE TITLE
Has the chart been published?

### ISSUE THREAD

**Issue by simonness** [EventStore/EventStore.Charts#2]
When running:

`> helm install stable/eventstore`

I get:

`Error: failed to download "eventstore" (hint: running `helm repo update` may help)`

**Comment by riccardone** [comment]
is not yet merged in the official stable repo. You can reference directly this repo I suppose. It's not ready yet for production but if you run some tests any feedback is much appreciate

**Comment by simonness** [comment]
Thanks @riccardone, no problem will let you know how I get on 👍

**Comment by andymeierdev** [comment]
@riccardone we should be able to publish the chart now. Following the instructions [here](https://github.com/helm/helm/blob/master/docs/chart_repository.md#github-pages-example) I think we just need to enable github pages and point to the `docs` directory.

**Comment by riccardone** [comment]
@ameier38 ok I've done that. Github pages are enabled and pointing to docs
The chart is published: https://eventstore.github.io/EventStore.Charts/

**Comment by andymeierdev** [comment]
Thanks @riccardone! I just confirmed I was able to add the repo and install. @simonness the docs have been updated now if you want to try it out.

**Comment by riccardone** [comment]
@ameier38 I wonder in what environment/cloud are you running your test?

**Comment by simonness** [comment]
@riccardone @ameier38 great thanks!  Confirm this worked for me now following the latest instructions in the readme.
