### ISSUE TITLE
Accessing EventStore external to the kubernetes cluster

### ISSUE THREAD

**Issue by stephanjohnson** [EventStore/EventStore.Charts#34]
Hi,

I've been working to migrate an environment (normal VM's) to use AKS over the last few weeks. Initially I was going to host EventStore on a VM outside of the cluster, while all of my workers lived inside of the cluster. That is until I saw that EventStore now has support to deploy into AKS. I figured that this would simplify my life (and Azure billing) and went down this path.

While all of the workers inside of the cluster can connect to the EventStore pods, the one thing that remains a bit of a thorn in my side is (_and this may be a design fault on my side_), my API which is hosted in an Azure Web App, is unable to connect to the EventStore from outside of the AKS cluster.

When I check the Kubernetes Dashboard, the EventStore has no ClusterIP, or External Endpoints, only Internal Endpoints.

I have followed the steps outlined [here](https://eventstore.org/docs/server/deploy-kubernetes-aks/index.html) with the exception that I have created and mounted my own persistence volume by using the persistence.existingClaim property while installing the Helm chart.

```
helm install -n eventstore eventstore/eventstore --set persistence.enabled=true,persistence.existingClaim=my-persistence-volume,'admin.password=XXXXXXXXXXXXXXXX'
```
My question is this:
Is there a way to expose the EventStore outside of the cluster so that my Azure Web App can connect to and use it? 
OR
Is the better design decision to add a RESTful API hosted inside of the cluster that talks to the EventStore, and my Azure Web App posts messages to that endpoint?

I am unsure of the way forward here. Any assistance would be greatly appreciated.

Regards,

Stephan

**Comment by riccardone** [comment]
My personal view is to use a channel adapter (a RESTful simple pass through API can do that) to expose it to the external world. I didn't try yet to deploy an ingress or similar service to make it visible

**Comment by stephanjohnson** [comment]
Hi @riccardone,

Thanks for the prompt response. This is what I was thinking, mostly because it removes the dependencies from my API and moves it into a simpler interface.

Regards,

Stephan
