### ISSUE TITLE
Upgrade to 5.0.1

### ISSUE THREAD

**Issue by krishofmans** [EventStore/EventStore.Charts#35]
Hi,

I just wanted to check if we are able to update the image value in the helm chart to 5.0.1 and if that should "just work" or will other changes be necessary?

If there a timeline on an updated version of the chart?

Thanks,
Kris

**Comment by riccardone** [comment]
It will just work. There is not a timeline but it's going to happen soon. In the meantime you can fork, make that change and then use your public fork as Chart

**Comment by krishofmans** [comment]
Great thanks for the information 

I `helm upgrade --set persistence.enabled=true --set imageTag=release-5.0.1 eventstore eventstore/eventstore` and it upgraded succesfully, it didn't seem to do a rolling update as I had some 502's but fine for now as it's not a production setup.
