### ISSUE TITLE
EventStore in Kubernetes using Helm Chart

### ISSUE THREAD

**Issue by wooderz** [EventStore/EventStore.Charts#38]
Is it possible to set the TCP connection to be secure? I can access my admin interface using an ingress setup with LetsEncrypt - is it possible to connect via the .net sdk in a secure way? Currently I'm using the connection settings:

```
var userCredentials = new UserCredentials("admin", "changeit");
            var connectionSettingsBuilder = ConnectionSettings
                .Create()
                .SetDefaultUserCredentials(userCredentials)
                .UseSslConnection("<SSL DOMAIN>", true)
                .EnableVerboseLogging()
                .UseConsoleLogger()
                .Build();
            
            var connection = EventStoreConnection.Create(connectionSettingsBuilder, new IPEndPoint(IPAddress.Parse("<INGRESS IP>"), 1113));
```

But that fails saying the connection was closed, removing the `.UseSslConnection` part makes it work hunky dory.

Have I missed something?

**Comment by gregoryyoung** [comment]
Have you enabled ssl for tcp? What is your command line?

**Comment by wooderz** [comment]
I'm using a Mac locally. EventStore is hosted in Kubernetes and was installed using the Helm chart. When we're in production it'll be in an AWS Lambda.

I've used CertManager to get LetsEncrypt certificates for the ingress, so have a cert stored in a Kube secret.

I thought I'd opened SSL for TCP in Kubernetes but I'm investigating deeper to find out!

**Comment by riccardone** [comment]
If you install EventStore with the default Helm Chart values it does not configure ssl automatically. You need to pass some parameters to the Helm Chart using the eventStoreConfig param. 

The settings to be used to configure ssl will be something similar to:
CertificateStoreLocation: CurrentUser
CertificateStoreName: My
CertificateThumbPrint: {Insert Thumb Print from Step 1}
CertificateSubjectName: CN=eventstore.org
ExtSecureTcpPort: 1115

https://eventstore.org/docs/server/setting-up-ssl/index.html?tabs=tabid-6%2Ctabid-8

**Comment by wooderz** [comment]
@riccardone thanks - so would those values actually correspond somehow with my Certificate stored in a Kube Secret? For example in my ingress I access the certificate via:

```
tls:
    - hosts:
        - <host_url>
      secretName: <certmanager_issuer_key_secret_ref>
```

I'm assuming that same certificate that's using my outbound url can work here? Or so I need to somehow create a new certificate for Kubernetes/HELM to use?

**Comment by wooderz** [comment]
The link in the docs looks to be for self signed certs? Doesn't sound right for production? 

I feel I've completely missed something here, so forgive me

**Comment by riccardone** [comment]
how you obtain your certificate is not relevant (just skip the certificate creation in the linked doc)

I suggest you to practice with self signed on a dev box without helm chart and kubernetes

then apply the settings in kubernetes/helm chart (yes the cert name need to correspond)

**Comment by wooderz** [comment]
Unfortunately the docs don't work on Mac - so I'm a bit stuck there if I'm to continue with SSL

**Comment by wooderz** [comment]
OK I'm just going to run under non SSL for the time being. If someone in the know could put up some docs on how to get SSL running in Kubernetes using the HELM chart alongside Cert-Manager and LetsEncrypt - that'd be amazing.
